### ISSUE TITLE
Missing steps in the tutorial

### ISSUE THREAD

**Issue by 3ueb** [ionic-team/tutorial-photo-gallery-angular#70]
You are using lazy loading for modules. So you have to configure and create the files` apps/app-routing.module.ts` and 
`tabs-routing.module.ts `. I believe this documentation is missing in your tutorial, and the first page, "Taking Photos" is not working.

**Comment by jcesarmobile** [comment]
I followed the tutorial and everything is working.
The app has those files already, if you choose ngModules option, maybe when you created the app it was creating standalone apps, but that was fixed in Ionic CLI, but you can follow the tutorial even if you create a standalone app, those files you mention won't be there, but they are not needed in standalone apps and not mentioned in the tutorial.
